services:
  db:
    image: postgis/postgis:latest
    container_name: DB.PARTNER.FINDER
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: evaaldo
      POSTGRES_PASSWORD: "230520"
      POSTGRES_DB: partner_finder
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
